package:
  name: arvados-cli
  version: "2.7.0"
build:
  number: 0
  skip: True # [osx]
source:
  url: https://rubygems.org/downloads/arvados-cli-2.7.0.gem
  sha256: 10fcd5ef6a09d3a31de4c8dd4afd3db593044c2c581ba6292547d78e56e6feba
requirements:
  build:
    - ruby >=2.6
    - curl
    - make
    - zlib
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
  run:
    - curl
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
test:
  commands:
    - "arv-tag --help 2>&1 | grep 'ARVADOS'"
about:
  home: http://doc.arvados.org/sdk/cli/index.html
  license: Apache v2
  summary: Command line interface to Arvados, a free and open source platform for big data science
